# -*- Makefile -*-


# This C project builds a program called "hello"
MAIN            := hello

# Inherit recurive build behaviors from parent
include ../$(word $(words $(MAKEFILE_LIST)),$(MAKEFILE_LIST))

